//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeePortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Employee
    {
        
        public int emp_id { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please input alphabet only!!"), MaxLength(50)]
        public string first_name { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please input alphabet only!!"), MaxLength(50)]
        public string last_name { get; set; }
        [Required(ErrorMessage = "Please input valid gender!")]
        public string gender { get; set; }
        [Required]
        [DataType(DataType.DateTime)]       
        public System.DateTime dob { get; set; }
        [Required]
        public string pan_num { get; set; }
        [Required]
        public string aadhaar_num { get; set; }
        [Required(ErrorMessage = "Please enter monile No")]         
        [DataType(DataType.PhoneNumber)]
        public string mobile_num { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Please enter valid Email ID")]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Email is not valid.")]
        public string email_id { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Please enter valid Email ID")]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Email is not valid.")]
        public string office_mail { get; set; }
        [MaxLength(200, ErrorMessage = "The Permanent Address cannot be more than 200 characters")]         
        public string permanent_address { get; set; }
        [MaxLength(200, ErrorMessage = "The Present Address cannot be more than 200 characters")]
        public string present_address { get; set; }
        [Required(ErrorMessage = "Please blood group!")]
        public string blood_group { get; set; }        
        public string profile_pict { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}")]
        public System.DateTime doj { get; set; }
        [Required(ErrorMessage = "Please sEnter Employee Level")]  
        [Range(7, 13, ErrorMessage = "Please select a value between 7 to 13!")]
        public int emp_level { get; set; }
        [Required]
        public string post_name { get; set; }
        [Required(ErrorMessage= "Please input numeric only!")]
        [DataType(DataType.Currency)]
        [Range(3, 8,ErrorMessage = "Please input  between 3 to 8  characters!!")]
        public int basic_pay { get; set; }
        [Required(ErrorMessage = "Please input numeric only!")]
        [DataType(DataType.Currency)]
        [Range(3, 5, ErrorMessage= "Please input  between 3 to 5  characters!!")]
        public int house_allowance { get; set; }
    
        public virtual Employment_history Employment_history { get; set; }
    }
}
