//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employment_history
    {
        public int id { get; set; }
        public int emp_id { get; set; }
        public string organization_name { get; set; }
        public System.DateTime from_date { get; set; }
        public System.DateTime until_date { get; set; }
        public string location { get; set; }
        public string country { get; set; }
        public string post { get; set; }
        public string skill_used { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
